import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

//Interフォントを設定し、ラテン文字のサブセットを使用するようにしています。
const inter = Inter({ subsets: ["latin"] });

// ページのタイトルや説明を設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* interは、`Inter`というGoogleフォントをNext.jsの`next/font/google`からインポートして設定したもの
      inter.classNameは、このフォントを適用するためのCSSクラス名を指しています。これを`<body>タグに適用することで、ページ全体にInter`フォントが適用されます。 */}
      <body className={inter.className}>
        <Header />
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false} // プログレスバーを表示（falseで表示）
          newestOnTop={false} // 新しい通知が上に表示される
          closeOnClick // クリックで閉じる
          rtl={false} // 右から左への表示（falseで左から右へ）
          pauseOnFocusLoss // ウィンドウのフォーカスが外れたときに自動閉じを一時停止しない
          pauseOnHover // マウスホバー時に自動閉じのタイマーを一時停止する
        />
      </body>
    </html>
  );
}
