import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import { Footer } from "./_components/Footer";

//Interフォントを設定し、ラテン文字のサブセットを使用するようにしています。
const inter = Inter({ subsets: ["latin"] });

// ページのタイトルや説明を設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* interは、`Inter`というGoogleフォントをNext.jsの`next/font/google`からインポートして設定したもの
      inter.classNameは、このフォントを適用するためのCSSクラス名を指しています。これを`<body>タグに適用することで、ページ全体にInter`フォントが適用されます。 */}
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
